// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgfNPjnwbqjshxLUlEWWuDCN3P0Fs5QC8',
    appId: '1:399529334438:web:8ac2c3e8be31057f874667',
    messagingSenderId: '399529334438',
    projectId: 'swatch-sewak',
    authDomain: 'swatch-sewak.firebaseapp.com',
    storageBucket: 'swatch-sewak.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_pZF22CstQlJYMdyGlmoc-BnebgXnVM',
    appId: '1:399529334438:android:7cee4413eefe9e0f874667',
    messagingSenderId: '399529334438',
    projectId: 'swatch-sewak',
    storageBucket: 'swatch-sewak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uNNLJfY4szYob4WWiZaq21O0UNR9kaw',
    appId: '1:399529334438:ios:c6edf9a05f26a748874667',
    messagingSenderId: '399529334438',
    projectId: 'swatch-sewak',
    storageBucket: 'swatch-sewak.firebasestorage.app',
    iosBundleId: 'com.akshat.Swatch-Sewak.swatchSewak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2uNNLJfY4szYob4WWiZaq21O0UNR9kaw',
    appId: '1:399529334438:ios:c6edf9a05f26a748874667',
    messagingSenderId: '399529334438',
    projectId: 'swatch-sewak',
    storageBucket: 'swatch-sewak.firebasestorage.app',
    iosBundleId: 'com.akshat.Swatch-Sewak.swatchSewak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgfNPjnwbqjshxLUlEWWuDCN3P0Fs5QC8',
    appId: '1:399529334438:web:310674aa422134b7874667',
    messagingSenderId: '399529334438',
    projectId: 'swatch-sewak',
    authDomain: 'swatch-sewak.firebaseapp.com',
    storageBucket: 'swatch-sewak.firebasestorage.app',
  );
}
